[versions]
ireader = "1.5.0"
ktor = "3.3.2"
ktlint = "0.45.1"
kotlin = "2.2.21"
serialization = "1.9.0"
ksp = "2.3.2"
serializationkotlinVersion = "1.7.10"
junitAndroidExtVersion = "1.1.4-alpha03"
dex2jar = "2.4.33"
ksoup = "0.2.5"
kotlinx-datetime = "0.7.1"

[libraries]
# Android/Gradle build tools
android-sdklib = "com.android.tools:sdklib:31.13.1"
android-gradle = "com.android.tools.build:gradle:8.13.1"

# Ktor (KMP HTTP client)
ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-android = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
ktor-client-js = { module = "io.ktor:ktor-client-js", version.ref = "ktor" }
ktor-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-contentNegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

# KotlinPoet (code generation)
kotlinpoet = "com.squareup:kotlinpoet-ksp:2.2.0"

# IReader core
ireader-core = { module = "io.github.ireaderorg:source-api", version.ref = "ireader" }

# Ksoup (KMP HTML parser - replaces Jsoup)
ksoup = { module = "com.fleeksoft.ksoup:ksoup", version.ref = "ksoup" }
ksoup-network = { module = "com.fleeksoft.ksoup:ksoup-network", version.ref = "ksoup" }

# KotlinX DateTime (KMP date/time)
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }

# Kotlin
gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }

# KSP
ksp-api = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
ksp-gradle = { module = "com.google.devtools.ksp:symbol-processing-gradle-plugin", version.ref = "ksp" }

# Serialization
serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
serialization-gradle = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }

# Testing
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
junit4 = "junit:junit:4.13.2"
extJunit = "androidx.test.ext:junit:1.3.0"
espresso = "androidx.test.espresso:espresso-core:3.7.0"
junitAndroidExt = "androidx.test.ext:junit:1.3.0"
coroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-test:1.10.2"
truth = "com.google.truth:truth:1.4.5"
testRunner = "androidx.test:runner:1.7.0"
robolectric = "org.robolectric:robolectric:4.16"

# Dex2Jar (for APK processing)
asm = "org.ow2.asm:asm:9.9"
dex2jar-translator = { module = "de.femtopedia.dex2jar:dex-translator", version.ref = "dex2jar" }
dex2jar-tools = { module = "de.femtopedia.dex2jar:dex-tools", version.ref = "dex2jar" }

[bundles]
# KMP common dependencies (for multiplatform sources)
kmp-common = ["ksoup", "ktor-core", "kotlinx-datetime", "ireader-core", "serialization-json"]
kmp-jvm = ["ktor-cio", "ktor-okhttp"]
kmp-js = ["ktor-client-js"]
kmp-android = ["ktor-android"]

# Testing
commonTesting = ["junit4", "extJunit", "espresso", "junitAndroidExt", "truth", "testRunner", "robolectric"]

[plugins]
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
