name: Docker Build Stable

on:
  release:
    types: [published]
  
jobs:
  build_publish_docker_container:
    runs-on: ubuntu-latest

    steps:         
      - name: run docker build and publish script
        run: |
          curl -X POST -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ secrets.DEPLOY_TOKEN }}" -d '{"ref":"main", "inputs":{"tachidesk_release_type": "stable"}}' https://api.github.com/repos/mpdr200011/Suwayomi-Server-docker/actions/workflows/build_container_images.yml/dispatches
          
