name: Docker Build Stable

on:
  release:
    types: [published]
  
jobs:
  build_publish_docker_container:
    uses: ./.github/workflows/container.yml
    with:
      tachidesk_release_type: stable
      do_upload: true
          
