name: Docker Build Stable

on:
  release:
    types: [published]
  
jobs:
  build_publish_docker_container:
    runs-on: ubuntu-latest
    uses: ./github/workflows/container.yml@master
    with:
      tachidesk_release_type: stable
      do_upload: true
          
